### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by smat-al** [andrey-yantsen/tlscontact-appointment-finder#5]
i need one for mooccan tlscontact
what should i do please
https://visa-fr.tlscontact.com/ma/CAS/index.php
thanks a lot

**Comment by andrey-yantsen** [comment]
Hey @smat-al, thanks for reaching out!

Unfortunately, I have no plans on improving the project. Feel free to add the required functionality and send a PR though.

**Comment by smat-al** [comment]
thanks, i will try to fix it .
